name: Primeiro Workflow

on:
    workflow_dispatch

jobs:
    giropops:
        runs-on: ubuntu-latest
        steps:
            - name: Confere versao Ubuntu
              run: cat /etc/os-release

            - name: Exibir msg
              run: echo "Teste do meu primeiro workflow"