name: Vendo arquivos compartilhados entre Steps

on:
    push:
        branches:
         - main

jobs:
    job_1:
      runs-on: ubuntu-latest
      steps:
        - name: Confere versao Ubuntu
          run: cat /etc/os-release

        - name: Exibir msg
          run: echo "Teste do meu primeiro workflow" > msg.txt

    job_2:
      runs-on: ubuntu-latest
      steps:
        - name: Another brick on the wall
          run: ls -lha
        - name: Acessa arquivo msg
          run: cat msg.txt