name: Vendo arquivos compartilhados entre Steps

on:
    push:
        branches:
         - main

jobs:
    entre-steps:
        runs-on: ubuntu-latest
        steps:
            - name: Confere versao Ubuntu
              run: cat /etc/os-release

            - name: Exibir msg
              run: echo "Teste do meu primeiro workflow" > msg.txt

            - name: Another brick on the wall
              run: ls -lha

            - name: Le conteudo do arquivo
              run: cat msg.txt